kind: Pod
apiVersion: v1
metadata:
  name: nginx-secret-pod

spec:
  containers:
    - name: nginx-secret-cont
      image: nginx:latest
      ports:
        - containerPort: 80

      env:
        - name: db-credential
          valueFrom:
            secretKeyRef:
              name: db-credential
              key: DB_USER

