kind: Pod
apiVersion: v1
metadata:
  name: secret-volume-nginx

spec:
  containers:
  - name: secret-volume
    image: nginx:latest
    ports:
      - containerPort: 80

    volumeMounts:
      - name: db-credential
        mountPath: "/mnt/data/nginx-secret"
        readOnly: true
  volumes:
  - name: db-credential
    secret:
        secretName: db-credential
